In [1]:
print("HEllo World")

HEllo World

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df_uci=pd.read_csv(r"C:\Users\Latha E\Heart_ML\datasets\uci_heart.csv")
df_uci

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,target
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,54,Female,VA Long Beach,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,NaN,NaN,1
916,917,62,Male,VA Long Beach,typical angina,NaN,139.0,False,st-t abnormality,NaN,NaN,NaN,NaN,NaN,NaN,0
917,918,55,Male,VA Long Beach,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,NaN,NaN,fixed defect,2
918,919,58,Male,VA Long Beach,asymptomatic,NaN,385.0,True,lv hypertrophy,NaN,NaN,NaN,NaN,NaN,NaN,0
919,920,62,Male,VA Long Beach,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,NaN,NaN,1

In [4]:
df_statlog=pd.read_csv(r"C:\Users\Latha E\Heart_ML\datasets\statlog_heart.csv")
df_statlog

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,3,130,322,0,2,109,0,2.4,1,3,1,1
1,67,0,2,115,564,0,2,160,0,1.6,1,0,3,0
2,57,1,1,124,261,0,0,141,0,0.3,0,0,3,1
3,64,1,3,128,263,0,0,105,1,0.2,1,1,3,0
4,74,0,1,120,269,0,2,121,1,0.2,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,2,172,199,1,0,162,0,0.5,0,0,3,0
266,44,1,1,120,263,0,0,173,0,0.0,0,0,3,0
267,56,0,1,140,294,0,2,153,0,1.3,1,0,1,0
268,57,1,3,140,192,0,0,148,0,0.4,1,0,2,0
269,67,1,3,160,286,0,2,108,1,1.5,1,3,1,1

PREPROCESSING UCI DATASET

In [5]:
df_uci.shape

(920, 16)

In [6]:
df_uci

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,target
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,54,Female,VA Long Beach,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,NaN,NaN,1
916,917,62,Male,VA Long Beach,typical angina,NaN,139.0,False,st-t abnormality,NaN,NaN,NaN,NaN,NaN,NaN,0
917,918,55,Male,VA Long Beach,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,NaN,NaN,fixed defect,2
918,919,58,Male,VA Long Beach,asymptomatic,NaN,385.0,True,lv hypertrophy,NaN,NaN,NaN,NaN,NaN,NaN,0
919,920,62,Male,VA Long Beach,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,NaN,NaN,1

In [7]:
df_uci=df_uci.drop("id",axis=1)

In [8]:
df_uci

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,target
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,54,Female,VA Long Beach,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,NaN,NaN,1
916,62,Male,VA Long Beach,typical angina,NaN,139.0,False,st-t abnormality,NaN,NaN,NaN,NaN,NaN,NaN,0
917,55,Male,VA Long Beach,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,NaN,NaN,fixed defect,2
918,58,Male,VA Long Beach,asymptomatic,NaN,385.0,True,lv hypertrophy,NaN,NaN,NaN,NaN,NaN,NaN,0
919,62,Male,VA Long Beach,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,NaN,NaN,1

In [9]:

print("Missing value count:\n",df_uci.isnull().sum(),"\n")
missing_percentage = (df_uci.isnull().sum() / len(df_uci)) * 100
print("Missing Percentage:\n", missing_percentage)

Missing value count:
 age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
target        0
dtype: int64

Missing Percentage:
 age          0.000000
sex          0.000000
dataset      0.000000
cp           0.000000
trestbps     6.413043
chol         3.260870
fbs          9.782609
restecg      0.217391
thalch       5.978261
exang        5.978261
oldpeak      6.739130
slope       33.586957
ca          66.413043
thal        52.826087
target       0.000000
dtype: float64

UNDERSTANDING THE IMPORTANCE OF A FEATURE AND HANDLING MISSING VALUES (2 Approaches)

1) Data Cleaning Basic

In [11]:
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer



# Copy original dataset for both approaches
df_basic = df_uci.copy()


# ==================================
# 🟢 APPROACH 1: BASIC CLEANING
# ==================================

# Impute missing values using mean/median/mode
basic_impute_dict = {
    'trestbps': df_basic['trestbps'].median(),
    'chol': df_basic['chol'].median(),
    'thalch': df_basic['thalch'].median(),
    'oldpeak': df_basic['oldpeak'].median(),
    'fbs': df_basic['fbs'].mode()[0],
    'restecg': df_basic['restecg'].mode()[0],
    'exang': df_basic['exang'].mode()[0]
}

# Apply imputation
df_basic.fillna(basic_impute_dict, inplace=True)

# Drop highly missing columns (optional)
df_basic.drop(columns=['ca', 'thal', 'slope'], inplace=True)  

# Save cleaned dataset
df_basic.to_csv("heart_disease_cleaned_basic.csv", index=False)

C:\Users\Latha E\AppData\Local\Temp\ipykernel_31712\3330057296.py:27: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_basic.fillna(basic_impute_dict, inplace=True)

Columns ca, thal, slope are dropped (>100 missing records)

Remaining missing data are handled using MMM imputation

2) Advanced Data Cleaning based on Importance

In [13]:
from sklearn.preprocessing import LabelEncoder

df_advanced = df_uci.copy()
df_advanced.astype(str)
knn_cols = ["ca", "thal", "slope"]

# Convert categorical values to numeric before KNN
label_encoders = {}
for col in knn_cols:
    df_advanced[col] = df_advanced[col].astype(str)  # Ensure string type
    le = LabelEncoder()
    df_advanced[col] = le.fit_transform(df_advanced[col])
    label_encoders[col] = le  # Store encoder for inverse transformation if needed

In [15]:
# Columns for different imputation techniques
knn_cols = ['ca', 'thal', 'slope']  # Highly missing but important
mice_cols = ['trestbps', 'chol', 'thalch', 'oldpeak']  # Continuous with patterns
mode_cols = ['fbs', 'restecg', 'exang']  # Categorical

# ==================================
# 🔵 APPROACH 2: ADVANCED CLEANING
# ==================================

# KNN Imputation for highly missing but important features
knn_imputer = KNNImputer(n_neighbors=5)
df_advanced[knn_cols] = knn_imputer.fit_transform(df_advanced[knn_cols])

# Round categorical values back to integers
df_advanced[knn_cols] = df_advanced[knn_cols].round(0).astype(int)

# MICE (Iterative Imputer) for continuous data
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_advanced[mice_cols] = mice_imputer.fit_transform(df_advanced[mice_cols])

# Mode Imputation for categorical variables
for col in mode_cols:
    df_advanced[col].fillna(df_advanced[col].mode()[0], inplace=True)

# Save cleaned dataset
df_advanced.to_csv("heart_disease_cleaned_advanced.csv", index=False)

C:\Users\Latha E\AppData\Local\Temp\ipykernel_31712\4243492667.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_advanced[col].fillna(df_advanced[col].mode()[0], inplace=True)
C:\Users\Latha E\AppData\Local\Temp\ipykernel_31712\4243492667.py:23: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_advanced[col].fillna(df_advanced[col].mode()[0], inplace=True)

MICE imputation for continuous features (trestbps, chol, thalch, oldpeak).

Mode imputation for categorical features (fbs, restecg, exang).

KNN imputation for thal, ca, and slope

3) Optimized Advanced using MICE for ca, thal, slope

In [16]:
from sklearn.impute import KNNImputer, SimpleImputer
df_advanced_1 = df_uci.copy()
df_advanced_1.astype(str)
mice_cols = ["ca", "thal", "slope"]

# Convert categorical values to numeric before KNN
label_encoders = {}
for col in mice_cols:
    df_advanced_1[col] = df_advanced_1[col].astype(str)  # Ensure string type
    le = LabelEncoder()
    df_advanced_1[col] = le.fit_transform(df_advanced_1[col])
    label_encoders[col] = le  # Store encoder for inverse transformation if needed

# 1️⃣ **MICE Imputation for `ca`, `thal`, `slope` (Highly missing but important)**
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
mice_cols = ["ca", "thal", "slope"]
df_advanced_1[mice_cols] = mice_imputer.fit_transform(df_advanced_1[mice_cols])

# 2️⃣ **KNN Imputation for `trestbps`, `chol`, `thalch`, `oldpeak` (Continuous features with patterns)**
knn_imputer = KNNImputer(n_neighbors=5)
knn_cols = ["trestbps", "chol", "thalch", "oldpeak"]
df_advanced_1[knn_cols] = knn_imputer.fit_transform(df_advanced_1[knn_cols])

# 3️⃣ **Mode Imputation for `fbs`, `restecg`, `exang` (Categorical features)**
mode_imputer = SimpleImputer(strategy="most_frequent")
mode_cols = ["fbs", "restecg", "exang"]
df_advanced_1[mode_cols] = mode_imputer.fit_transform(df_advanced_1[mode_cols])

# Save the cleaned dataset
df_advanced_1.to_csv("_optimized_advanced_heart_disease_cleaned.csv", index=False)

✅ MICE (Multiple Imputation by Chained Equations) for ca, thal, slope

These categorical features have high missing values but are important for heart disease prediction.
MICE is good for categorical features because it models missing values based on other feature relationships iteratively.

✅ KNN Imputation for trestbps, chol, thalch, oldpeak

These are continuous features, and KNN is effective for finding similar patterns in existing data to fill in missing values.
KNN uses similar neighbors, making it better for structured numerical data.

✅ Mode Imputation for fbs, restecg, exang

These are categorical variables with low missing values, and the mode (most frequent value) is a simple but effective way to handle them.